name: STG - Deployment to TestFlight
# STG로 시작하는 태그가 Push되면 workflow 동작
on:
  push:
    tags:
      - STG*

jobs:
  deploy:
    runs-on: macos-latest

    env:
      XC_PROJECT: ${{ 'cicd-ios/cicd-ios.xcodeproj' }}

    steps:
      - name: Select latest Xcode
        run: "sudo xcode-select -s /Applications/Xcode.app"
      
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Archive app
        run: |
          xcodebuild clean archive -project $XC_PROJECT
      
      # - name: Upload app to TestFlight
      #   uses: apple-actions/upload-testflight-build@v1
      #   with:
      #     app-path: 'HappyChuseok.ipa'
      #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APPSTORE_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}